import type { Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            {/* 로그인 안된 경우 */}
            <SignedOut>
              <SignInButton>
                <button className="bg-blue-500 text-white px-4 py-2 rounded">
                  Sign In
                </button>
              </SignInButton>
              <SignUpButton>
                <button className="bg-purple-600 text-white px-4 py-2 rounded">
                  Sign Up
                </button>
              </SignUpButton>
            </SignedOut>

            {/* 로그인된 경우 */}
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>

          {/* 홈 화면 렌더링 */}
          <SignedIn>{children}</SignedIn>

          {/* 로그인 안된 경우 안내 화면 */}
          <SignedOut>
            <div className="flex items-center justify-center h-[80vh]">
              <p className="text-xl font-semibold">로그인을 해주세요.</p>
            </div>
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  )
}
